on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.1'
          dest: '"${HOME}/racketdist"'
          local_catalogs: $GITHUB_WORKSPACE
          sudo: never
      - name: Register local packages
        run: |
          raco pkg install -i --auto --no-setup --skip-installed super
          raco pkg update  --auto --no-setup super
      - name: Setup Collections
        run: raco setup --check-pkg-deps super
