on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.5'
          dest: '"${HOME}/racketdist"'
          local_catalogs: $GITHUB_WORKSPACE
          sudo: never
      - name: Register local packages
        run: |
          raco pkg install --name super
      - name: Setup Collections
        run: raco setup --check-pkg-deps super
